Resources:
  Backend:
    Type: 'AWS::EC2::Instance'
    Properties:
      SecurityGroupIds:
        - sg-0f094658168d4f74b
      ImageId: ami-04a0ae173da5807d3
      KeyName: backendkeypair
      InstanceType: t2.micro
      SubnetId: subnet-033083c73e528f20c
      AvailabilityZone: us-east-1a      
      Tags:
        - Key: Name
          Value: Databox
      UserData: !Base64 
        'Fn::Sub': |
          #!/bin/bash
          yum update
          yum -y install nginx
          sudo systemctl restart nginx.service
      BlockDeviceMappings:
      -
        DeviceName: /dev/xvda
        Ebs:
          VolumeSize: 8
